CREATE TABLE `address` (
  `AddressID` INT NOT NULL AUTO_INCREMENT,
  `AddressLine1` VARCHAR(60) NOT NULL,
  `AddressLine2` VARCHAR(60) DEFAULT NULL,
  `City` VARCHAR(30) NOT NULL,
  `StateProvinceID` INT NOT NULL,
  `PostalCode` VARCHAR(15) NOT NULL,
  `rowguid` VARBINARY(16) NOT NULL,
  `ModifiedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (AddressID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb3,
COLLATE utf8mb3_general_ci;